### ISSUE TITLE
One Youtube video not loading

### ISSUE THREAD

**Issue by JohnBlackburne** [hoyois/clicktoplugin#108]
I spend too much time on YouTube. Found another which seems not to load HTML5, only Flash. Nothing odd I can see about the name or heading: "Dire Straits - Romeo & Juliet (Original Video 1981) (HQ 16:9)". Tried restarting Safari in case but it's still not loading, still the only one:

https://www.youtube.com/watch?v=QkfotbNqQgw

**Comment by hoyois** [comment]
Thanks. The problem is that the get_video_info page returns an error along the lines of "the uploader has not made the video available on other websites". I have experienced this once before with a specific video, but the problem disappeared after a week or so. I suspect these occurrences are bugs on YouTube's side, since the way CTP accesses the get_video_info page works on almost 100% of videos, and certainly the uploader cannot prevent it.

I know a way to get video URLs without calling get_video_info, but it's messy and requires parsing some minified JS files to obtain the signature decoding algorithm. Unless the problem becomes widespread, I don't think it's worth it.

**Comment by JohnBlackburne** [comment]
Thanks. No, only one instance of it at the moment so certainly not worth spending more time on it

**Comment by JohnBlackburne** [comment]
Tried to look at it again but the video has been removed due to copyright issues, so there’s not even one now with this problem that I'm aware of.
