### ISSUE TITLE
Airplay youtube video stops randomly

### ISSUE THREAD

**Issue by khanmu29** [hoyois/clicktoplugin#138]
All youtube videos get sent seamlessly to the appleTV, however the playback will just cutout randomly, sometimes a minute in, sometimes five minutes in. At this point I just resend the video through clicktoplugin and I can forward to where it cut out because it seems to have kept that amount of video buffered. I love this plugin, but it would save me a lot of hassle if I didn't experience this issue.

**Comment by hoyois** [comment]
That would happen if you let your computer go to sleep, although it may well happen for other reasons. There is unfortunately nothing that can be done on my end, since CTP uses the only known way for a Safari extension to connect to an AirPlay device. The feature is what it is and can't be tinkered with.
